### PR TITLE
Draft: Static frontend implementation of results

### PR DESCRIPTION
**Pull request by jenishshrestha**
#190

### CODE REVIEW

**Comment by man-git007** [comment]
@jenishshrestha can we merge this PR?

**Comment by man-git007** [comment]
@jenishshrestha Lets close PR if these changes are already done or not required

**Comment by man-git007** [comment]
@jenishshrestha Can we close this PR?

cc @praweshsth @titungdup

**Comment by jenishshrestha** [comment]
No need to merge so closed manually.

**Pull request closed without merging**
